const cartActionTypes = {
    TOGGLE_HEADER_DROPDOWN_HIDDEN: 'TOGGLE_HEADER_DROPDOWN_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM: 'CLEAR_ITEM',
    CLEAR_ALL_ITEMS: 'CLEAR_ALL_ITEMS',
    ADD_ITEM_LOCALLY: 'ADD_ITEM_LOCALLY'
};

export default cartActionTypes;