const userActionTypes = {
    REQUEST_USER_UPDATES_FROM_FIREBASE: 'REQUEST_USER_UPDATES_FROM_FIREBASE',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT'
};

export default userActionTypes;